import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'contactPageSettings',
  title: 'Contact Page Settings',
  type: 'document',
  icon: () => '📞',
  fields: [
    defineField({
      name: 'title',
      title: 'Page Title',
      type: 'string',
      description: '📞 The main title for the contact page. This appears in browser tabs and search results.',
      validation: (Rule) => Rule.required(),
      initialValue: 'Contact Jennifer Watkins | Contemporary Artist',
    }),
    defineField({
      name: 'description',
      title: 'Page Description',
      type: 'text',
      rows: 3,
      description: '📝 Brief description for search engines and social media. Keep under 160 characters.',
      validation: (Rule) => Rule.required().max(160),
      initialValue: 'Get in touch with Jennifer Watkins for commissions, exhibitions, or general inquiries about contemporary art.',
    }),
    defineField({
      name: 'heroSection',
      title: '🎨 Hero Section',
      type: 'object',
      description: 'The banner section at the top of the contact page',
      fields: [
        {
          name: 'title',
          title: 'Page Heading',
          type: 'string',
          description: '✨ Main heading for the contact page',
          validation: (Rule) => Rule.required(),
          initialValue: 'Get in Touch',
        },
        {
          name: 'subtitle',
          title: 'Page Subtitle',
          type: 'text',
          rows: 3,
          description: '📖 Introductory text that appears below the main heading',
          initialValue: 'I\'d love to hear from you. Whether you\'re interested in commissioning a piece, discussing an exhibition opportunity, or simply want to connect about art.',
        },
      ],
    }),
    defineField({
      name: 'contactForm',
      title: '📝 Contact Form Settings',
      type: 'object',
      description: 'Configure the contact form fields and labels',
      fields: [
        {
          name: 'title',
          title: 'Form Title',
          type: 'string',
          description: '📝 Heading above the contact form',
          initialValue: 'Send a Message',
        },
        {
          name: 'subtitle',
          title: 'Form Description',
          type: 'text',
          rows: 2,
          description: '📖 Text explaining how to use the form',
          initialValue: 'Fill out the form below and I\'ll get back to you as soon as possible.',
        },
        {
          name: 'nameLabel',
          title: 'Name Field Label',
          type: 'string',
          description: '🏷️ Label for the name input field',
          initialValue: 'Full Name',
        },
        {
          name: 'emailLabel',
          title: 'Email Field Label',
          type: 'string',
          description: '🏷️ Label for the email input field',
          initialValue: 'Email Address',
        },
        {
          name: 'subjectLabel',
          title: 'Subject Field Label',
          type: 'string',
          description: '🏷️ Label for the subject input field',
          initialValue: 'Subject',
        },
        {
          name: 'messageLabel',
          title: 'Message Field Label',
          type: 'string',
          description: '🏷️ Label for the message textarea',
          initialValue: 'Message',
        },
        {
          name: 'submitButtonText',
          title: 'Submit Button Text',
          type: 'string',
          description: '🔘 Text for the form submit button',
          initialValue: 'Send Message',
        },
        {
          name: 'successMessage',
          title: 'Success Message',
          type: 'text',
          rows: 2,
          description: '✅ Message shown when form is submitted successfully',
          initialValue: 'Thank you for your message! I\'ll get back to you within 24-48 hours.',
        },
      ],
    }),
    defineField({
      name: 'inquiryTypes',
      title: '📋 Inquiry Types',
      type: 'array',
      of: [
        {
          type: 'object',
          fields: [
            {
              name: 'label',
              title: 'Inquiry Type',
              type: 'string',
              description: '📝 Name of the inquiry type',
            },
            {
              name: 'description',
              title: 'Description',
              type: 'string',
              description: '📖 Brief description of this inquiry type',
            },
          ],
        },
      ],
      description: '📋 Different types of inquiries visitors can select from',
      initialValue: [
        { label: 'Commission Inquiry', description: 'Custom artwork commissions' },
        { label: 'Purchase Inquiry', description: 'Buying existing artworks' },
        { label: 'Exhibition Opportunity', description: 'Gallery and exhibition proposals' },
        { label: 'Press & Media', description: 'Interviews and media requests' },
        { label: 'General Question', description: 'Other inquiries' },
      ],
    }),
    defineField({
      name: 'contactInfo',
      title: '📞 Contact Information',
      type: 'object',
      description: 'Direct contact details and studio information',
      fields: [
        {
          name: 'title',
          title: 'Section Title',
          type: 'string',
          description: '📞 Heading for the contact information section',
          initialValue: 'Contact Information',
        },
        {
          name: 'email',
          title: 'Email Address',
          type: 'string',
          description: '📧 Primary email address for contact',
          validation: (Rule) => Rule.email(),
        },
        {
          name: 'phone',
          title: 'Phone Number',
          type: 'string',
          description: '📱 Phone number (optional)',
        },
        {
          name: 'address',
          title: 'Studio Address',
          type: 'object',
          fields: [
            {
              name: 'street',
              title: 'Street Address',
              type: 'string',
            },
            {
              name: 'city',
              title: 'City',
              type: 'string',
            },
            {
              name: 'state',
              title: 'State/Province',
              type: 'string',
            },
            {
              name: 'zipCode',
              title: 'ZIP/Postal Code',
              type: 'string',
            },
            {
              name: 'country',
              title: 'Country',
              type: 'string',
            },
          ],
          description: '📍 Studio or business address',
        },
        {
          name: 'hours',
          title: 'Studio Hours',
          type: 'text',
          rows: 3,
          description: '🕒 When the studio is open for visits',
          initialValue: 'Studio visits by appointment only.\nPlease contact me to schedule a visit.',
        },
      ],
    }),
    defineField({
      name: 'socialMedia',
      title: '📱 Social Media Links',
      type: 'object',
      description: 'Social media profiles and links',
      fields: [
        {
          name: 'title',
          title: 'Section Title',
          type: 'string',
          description: '📱 Heading for the social media section',
          initialValue: 'Follow My Work',
        },
        {
          name: 'subtitle',
          title: 'Section Description',
          type: 'text',
          rows: 2,
          description: '📖 Text encouraging social media engagement',
          initialValue: 'Stay updated with my latest works and studio insights.',
        },
        {
          name: 'instagram',
          title: 'Instagram URL',
          type: 'url',
          description: '📷 Instagram profile link',
        },
        {
          name: 'facebook',
          title: 'Facebook URL',
          type: 'url',
          description: '👥 Facebook page link',
        },
        {
          name: 'twitter',
          title: 'Twitter URL',
          type: 'url',
          description: '🐦 Twitter profile link',
        },
        {
          name: 'linkedin',
          title: 'LinkedIn URL',
          type: 'url',
          description: '💼 LinkedIn profile link',
        },
        {
          name: 'website',
          title: 'Additional Website',
          type: 'url',
          description: '🌐 Additional website or portfolio link',
        },
      ],
    }),
    defineField({
      name: 'studioVisits',
      title: '🏠 Studio Visits Section',
      type: 'object',
      description: 'Information about visiting the studio',
      fields: [
        {
          name: 'title',
          title: 'Section Title',
          type: 'string',
          description: '🏠 Heading for the studio visits section',
          initialValue: 'Studio Visits',
        },
        {
          name: 'description',
          title: 'Visit Description',
          type: 'text',
          rows: 4,
          description: '📖 Information about studio visits and what to expect',
          initialValue: 'I welcome visitors to my studio by appointment. It\'s a wonderful opportunity to see works in progress, discuss commissions, and experience the creative process firsthand.',
        },
        {
          name: 'bookingInstructions',
          title: 'Booking Instructions',
          type: 'text',
          rows: 3,
          description: '📅 How to book a studio visit',
          initialValue: 'To schedule a visit, please contact me at least 48 hours in advance. I\'m available most weekdays and some weekends.',
        },
        {
          name: 'buttonText',
          title: 'Booking Button Text',
          type: 'string',
          description: '🔘 Text for the studio visit booking button',
          initialValue: 'Schedule a Visit',
        },
      ],
    }),
    defineField({
      name: 'commissions',
      title: '🎨 Commission Information',
      type: 'object',
      description: 'Information about commissioning artwork',
      fields: [
        {
          name: 'title',
          title: 'Section Title',
          type: 'string',
          description: '🎨 Heading for the commission section',
          initialValue: 'Commission a Piece',
        },
        {
          name: 'description',
          title: 'Commission Description',
          type: 'text',
          rows: 4,
          description: '📖 Information about the commission process',
          initialValue: 'I accept a limited number of commissions each year. Whether you\'re looking for a specific size, color palette, or theme, I work closely with clients to create meaningful, personalized artwork.',
        },
        {
          name: 'process',
          title: 'Commission Process',
          type: 'array',
          of: [{ type: 'string' }],
          description: '📋 Steps in the commission process',
          initialValue: [
            'Initial consultation to discuss your vision',
            'Proposal with timeline and pricing',
            'Sketches and concept approval',
            'Creation process with progress updates',
            'Final delivery and installation support',
          ],
        },
        {
          name: 'buttonText',
          title: 'Commission Button Text',
          type: 'string',
          description: '🔘 Text for the commission inquiry button',
          initialValue: 'Inquire About Commissions',
        },
      ],
    }),
    defineField({
      name: 'seo',
      title: '🔍 SEO Settings',
      type: 'object',
      description: 'Search engine optimization settings for the contact page',
      fields: [
        {
          name: 'metaTitle',
          title: 'Meta Title',
          type: 'string',
          description: '📝 Title that appears in search results (max 60 characters)',
          validation: (Rule) => Rule.max(60),
        },
        {
          name: 'metaDescription',
          title: 'Meta Description',
          type: 'text',
          rows: 3,
          description: '📝 Description that appears in search results (max 160 characters)',
          validation: (Rule) => Rule.max(160),
        },
        {
          name: 'keywords',
          title: 'Keywords',
          type: 'array',
          of: [{ type: 'string' }],
          description: '🏷️ Keywords for search engine optimization',
          options: {
            layout: 'tags',
          },
        },
        {
          name: 'ogImage',
          title: 'Social Media Image',
          type: 'image',
          description: '📷 Image that appears when the contact page is shared on social media',
          options: {
            hotspot: true,
          },
        },
      ],
    }),
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'description',
    },
    prepare(selection) {
      const { title, subtitle } = selection
      return {
        title: title || 'Contact Page Settings',
        subtitle: subtitle || 'Configure contact page content and layout',
      }
    },
  },
})
